name: First Workflow
on: workflow_dispatch # manually start the workflow
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | # have multiple lines
          echo "Hello world!" 
          echo "Hello world from Mars!"
      - name: Print goodbye
        run: echo "Done - bye!"

